title: 'Northeast HCI Meeting'
preposition: ''
description: >-
  Conference to host NE Region HCI Researchers Virtually and at Carnegie Mellon University May 8-10, 2024
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://northeasthcimeeting.info" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: false
    permalink: /:collection/:title/
  speakers:
    output: false
    permalink: /:collection/:title/
  rooms:
    output: false
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: False

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map: false

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true
  
  navigation:
    links:
      - name: Works in Progress Info
        relative_url: /worksinprogress/
